Webshop_Games/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webshop_Games.Data;
using Webshop_Games.Models;
using Webshop_Games.Logic;

namespace Webshop_Games.Controllers
{
    public class CustomerController : Controller
    {
        // GET: Customer
        [Authorize]
        public ActionResult OrdersList()
        {
            using (var db = new WebshopEntities())
            {
                var user = db.User.Where(x => x.email == User.Identity.Name).Select(x => x.id).FirstOrDefault();
                var proList = OrdersManager.GetCustomerOrders(user);

                return View(proList);
            }
        }
    }
}

Webshop_Games/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webshop_Games.Data;
using Webshop_Games.Models;
using Webshop_Games.Logic;

namespace Webshop_Games.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            var proList = ProductManager.GetProduct();

            var cat = new Dictionary<int, string>();

            using (var db = new WebshopEntities())
            {
                foreach (var item in db.Category)
                {
                    cat.Add(item.id, item.Name);
                }
            }

            TempData["Categories"] = cat;

            return View(proList);

            //return View(new List<Models.Product>());
           
        }

        [HttpGet]
        public ActionResult Search(int catId, string search)
        {
            List<Product_VM> products = new List<Product_VM>();
            if(catId != 1)
            {
                products = ProductManager.GetProduct().Where(x => x.Category_id == catId).ToList();
            }
            else
            {
                products = ProductManager.GetProduct();
            }
            if(search != null)
            {
                products = products.Where(x =>  x.Name.ToLower().Contains(search.ToLower()) || 
                                                x.Description.ToLower().Contains(search.ToLower()) ||
                                                x.CompanyName.ToLower().Contains(search.ToLower())).ToList();
            }

            var cat = new Dictionary<int, string>();

            using (var db = new WebshopEntities())
            {
                foreach (var item in db.Category)
                {
                    cat.Add(item.id, item.Name);
                }
            }

            TempData["Categories"] = cat;

            return View("Index", products);
        }
   
        public ActionResult Details(int id)
        {
            using (var db = new WebshopEntities())
            {
                var newCart = Session.GetCart();

                var details = db.Product.Where(x => x.id == id).SingleOrDefault();

                var newDetails = new Details_VM();

                newDetails.Id = details.id;
                newDetails.Name = details.Name;
                newDetails.Description = details.Description;
                newDetails.Price = details.Price;
                newDetails.ImagePath = details.ImagePath;
                newDetails.Company_id = db.Company.Where(x => x.id == details.Company_id).Select(x => x.id).FirstOrDefault(); ;
                newDetails.CompanyName = db.Company.Where(x => x.id == details.Company_id).Select(x => x.Name).FirstOrDefault();
                newDetails.Category_id = db.Category.Where(x => x.id == details.Category_id).Select(x => x.id).FirstOrDefault();
                newDetails.CategoryName = db.Category.Where(x => x.id == details.Category_id).Select(x => x.Name).FirstOrDefault();
                newDetails.Quantity = newCart.Cart.Where(x => x.Key == id).Select(x => x.Value).FirstOrDefault();

                return View(newDetails);
            }
        }
    }
}

Webshop_Games/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Webshop-Games", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Produkte", "Index", "Product")</li>
                    <li>@Html.ActionLink("Ihr Warenkorb", "Cart", "Cart")</li>
                    <li>@Html.ActionLink("Ihre Bestellungen", "OrdersList", "Customer")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Login/Registrieren", "Login", "Login")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer class="footer">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>&copy; @DateTime.Now.Year - Mein Spiele-Webshop Copyright Kavallar</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Kontakt", "Contact")</li>
                    <li>@Html.ActionLink("Impressum", "Impressum")</li>
                    <li>@Html.ActionLink("Datenschutzrichtlinie", "Datenschutz")</li>                    
                    <li>@Html.ActionLink("AGB", "AGB")</li>                
                </ul>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>